CREATE TABLE `sys_alipay_log` (
  `notify_id` varchar(50) DEFAULT NULL COMMENT '通知校验ID',
  `notify_type` varchar(20) DEFAULT NULL COMMENT '通知类型',
  `notify_time` datetime DEFAULT NULL COMMENT '通知时间',
  `trade_no` varchar(60) DEFAULT NULL COMMENT '支付宝交易号',
  `out_trade_no` varchar(60) DEFAULT NULL COMMENT '商户订单号',
  `trade_status` varchar(15) DEFAULT NULL COMMENT '交易状态',
  `subject` varchar(500) DEFAULT NULL COMMENT '订单标题',
  `gmt_create` datetime DEFAULT NULL COMMENT '交易创建时间',
  `gmt_payment` datetime DEFAULT NULL COMMENT '交易付款时间',
  `buyer_id` varchar(100) DEFAULT NULL COMMENT '买家支付宝用户号',
  `invoice_amount` decimal(10,2) DEFAULT NULL COMMENT '开票金额',
  `total_amount` decimal(10,2) DEFAULT NULL COMMENT '订单金额',
  `receipt_amount` decimal(10,2) DEFAULT NULL COMMENT '实收金额',
  `point_amount` decimal(10,2) DEFAULT NULL COMMENT '集分宝金额',
  `buyer_pay_amount` decimal(10,2) DEFAULT NULL COMMENT '付款金额',
  `seller_id` varchar(50) DEFAULT NULL COMMENT '卖家支付宝用户号',
  `fund_bill_list` varchar(500) DEFAULT NULL COMMENT '支付金额信息',
  `auth_app_id` varchar(100) DEFAULT NULL,
  `app_id` varchar(100) DEFAULT NULL COMMENT '开发者的app_id',
  `sign_type` varchar(10) DEFAULT NULL COMMENT '签名类型',
  `alipay_account` varchar(30) DEFAULT NULL COMMENT '收款支付宝账号',
  `refund_fee` decimal(10,2) DEFAULT NULL COMMENT '总退款金额',
  `gmt_refund` datetime DEFAULT NULL COMMENT '交易退款时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC